# Generated by Django 4.2.7 on 2023-12-01 17:55

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}),
        ),
    ]
