# Generated by Django 4.2.7 on 2023-12-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='catgory',
            new_name='category',
        ),
    ]
